CREATE TABLE IF NOT EXISTS location (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    lat DECIMAL(10, 8) NOT NULL,
    `long` DECIMAL(11, 8) NOT NULL,
    time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
); 